### ISSUE TITLE
当启用"Post data"的时候，Execute按钮不太好用

### ISSUE THREAD

**Issue by wstone0011** [khoiasd/hackbar#1]
不启用"Post data",点击Execute按钮可以跳转；启动"Post data"后，则无法跳转，用Burp Suite抓包，看不到数据包，既没有发出http请求。

**Comment by khoiasd** [comment]
Can you translate into English?

**Comment by wstone0011** [comment]
I'm sorry. My english is poor. Maybe you can understand it.
I say that the "Execute" button has some problems when the "Post data" is enabled.

My firefox version is 57.0.3 (32bit) for windows 7 x86_64.
HackerBar version is 1.1.3

![hackbar_problem](https://user-images.githubusercontent.com/12856083/34468704-91afbd84-ef49-11e7-83f3-7058755919e5.jpg)

**Comment by khoiasd** [comment]
Thanks for your report, I will fix it in next version

**Comment by wstone0011** [comment]
It's my pleasure.
