### ISSUE TITLE
cann't use post data fomart like submit=submit&ID=1

### ISSUE THREAD

**Issue by laogle** [khoiasd/hackbar#15]
cann't use post data fomart like submit=submit&ID=1

Failure to interpret  correctly

Ver 2.1

pls check this issue

**Comment by khoiasd** [comment]
Fixed,
Thanks for report. If has to pay 1$ for hackbar? will you continue to use it?

**Comment by Maks-s** [comment]
Of course nobody will use hackbar if they has to pay $1
