### ISSUE TITLE
Referrer, User Agent and Cookies NOT WORKING!

### ISSUE THREAD

**Issue by SecurityFlaw** [khoiasd/hackbar#17]
Referrer, User Agent and Cookies don't load.

**Comment by khoiasd** [comment]
Hi SecurityFlaw,
This issue on firefox or chrome?

**Comment by SecurityFlaw** [comment]
It's on Firefox. ATM on version 66.0.1

**Comment by SecurityFlaw** [comment]
Same on 66.0.2 (Firefox)
Cookies, Referrer and User-Agent don't show after clicking the Load URL Button.
Please fix it.

Encoding / Decoding have some errors, too:
URL Encoding / Decoding don't works.
HEX Encoding / Decoding don't works.
Please fix it too.

**Comment by khoiasd** [comment]
there issues were fixed, thanks for your comment
