### ISSUE TITLE
Hackbar cannot be launched because F12 is prioritized by Developer Tools

### ISSUE THREAD

**Issue by davidhedlund** [khoiasd/hackbar#2]
Firefox inbuilt Developer Tools (used by many options seen at Tools -> Web Developer) already uses Ctrl+Shift-C but also F12 as shortcut. I could not open Hackbar as a result when I evaluated this in Firefox 57.0.4.

**Comment by khoiasd** [comment]
Thanks for your comment, F12 is short cut open web Devtool panel. I cant find how to add shortcut for hackbar :(

**Comment by davidhedlund** [comment]
@khoiasd Can you please state that Hackbar is broken at https://addons.mozilla.org/en-US/firefox/addon/hackbartool/ until you have found a solution and fixed it?

**Comment by Sunxiangpeng0531** [comment]
@khoiasd Hi, my F12 is occupied by other program under ubuntu, How about adding a button on toolbar which can auto launch to hackbar after click?

**Comment by davidhedlund** [comment]
@Sunxiangpeng0531 https://github.com/khoiasd/hackbar/issues/4

**Comment by davidhedlund** [comment]
https://github.com/khoiasd/hackbar/issues/4
