### ISSUE TITLE
Does not load in a Firefox Portable.

### ISSUE THREAD

**Issue by tilt41** [khoiasd/hackbar#5]
I am running Firefox Portable from portableapps.com and when trying to load this extension I see the following:
Firefox can’t find the file at moz-extension://0b6b48a3-c52f-4e97-90c7-62d80ed2b2b2/theme/theme/hackbar-panel.html

When I install the extension into a local copy of Firefox it runs with no issues.

**Comment by vladimmi** [comment]
Same error but with local copy (non-portable):
```
Firefox can’t find the file at moz-extension://c61d35fa-7c14-40ed-89d7-9153ef1e441e/theme/theme/hackbar-panel.html
```

**Comment by lzskyline** [comment]
I have reinstalled hackbar just now and found that this problem has been fixed.
